### ISSUE TITLE
Invalid PDF file

### ISSUE THREAD

**Issue by ineiti** [pablojimenezmateo/curriculum-bootloader#2]
When clicking on the file in Github, it displays `Sorry, this file is invalid so it cannot be displayed.`

**Comment by kavu** [comment]
But if you download and open it (I am opening with Preview.app and Google Chrome on macOS) everything will open as intended. 🤔

**Comment by tiernano** [comment]
Tried opening on an iPhone and it suggests VLC. Other pdfs just open as normal in Safari...

**Comment by letalvoj** [comment]
> 1018 bytes, which is the perfect size since the PDF header has to be in the first 1024 bytes. 

```
cat boot.bin CV_english.pdf > cv.pdf
```

well it seems to me, that this could work only if the `CV_english.pdf` had a header of size 6. Is not it the case that you'd have to somehow merge the code to the actual header?

What about jumping somewhere in the middle of the PDF, where the actual code is going to be hidden inside an image? 🤔

**Comment by pablojimenezmateo** [comment]
Hi all,

my latest push should fix this issue, I have updated the instructions accordingly. If you don't mind trying again and let me know I would really appreciate, since I do not have an iPhone nor a macOS.

**Comment by pablojimenezmateo** [comment]
Just reopening until you can test :)

**Comment by tiernano** [comment]
Just checked and it still doesn't open in safari, but ends up opening in iBooks. So, it is readable. So, all good on my end!

**Comment by tiernano** [comment]
This is very cool, by the way! I have to try it as a boot loader now!

**Comment by pablojimenezmateo** [comment]
Interesting. Unfortunately I am unable to debug it for Safari, but I am glad that it works on iBooks :)

**Comment by pablojimenezmateo** [comment]
Hi,

as much as I would like to, I don't have the time to focus to fix all the PDF readers, hopefully I will find the time to look into why Adobe Reader does not work (since it is a major PDF reader) and this will also fix this compatibility. As of now I do not consider this an open issue since I do not plan to support Safari, so I am closing this issue.

Again, thanks for the feedback, hopefully I can revisit if I fix the Adobe problem.
